///
/// PersonService  (auto-generated by admin tool)
/// Person 서비스 테스트
///

import { Service, Sql, Log } from '../core/decorators.js';
import db from '../database/db.js';


@Service('PersonService')
export default class PersonService {

  // SQL 파일 주입: src/database/sql/person.sql
  @Sql('person') personSql;

  @Log log;

  // 전체 조회
  async list() {
    this.log.info(`${this.constructor.name}::list 호출됨`);
    const sql = this.personSql.get('findAll');
    const res = await db.execute(sql, {});
    return res.rows;
  }

  // 단건 조회
  async getById(id) {
    this.log.debug(`${this.constructor.name}::getById 호출됨 -> id=${id}`);
    const sql = this.personSql.get('findById');
    const res = await db.execute(sql, { id });
    return res.rows[0] ?? null;
  }

  // 생성
  async create(payload) {
    this.log.info(`${this.constructor.name}::create 호출됨`);
    const sql = this.personSql.get('insert');
    const res = await db.execute(sql, payload);
    return { insertId: res.insertId, rowsAffected: res.rowsAffected };
  }
}
