///
/// PersonController
/// Person 컨트롤러 테스트
/// (auto-generated by admin tool)
///

import {
  Controller,
  Log,
  GetMapping,
  Auth,
  Autowired,
} from '../core/decorators.js';


@Controller('/api/person')
export default class PersonController {

  @Autowired('PersonService') personService;

  @Log log;

  // 1. GET /api/person/  →  PersonController.list
  @GetMapping('/')
  @Auth()
  async list(params) {
    this.log.info(`${this.constructor.name}::list 호출됨`);
    const result = await this.personService.list();
    return result;
  }
}
